// Acá hay que agregar una función similar a la que ocupa N8N que parsea el JSON... 
// Esto se tiene que hacer para cada uno, lo que se tiene que aplicar a cada uno de los campos que estamos solicitando... 
// Tiene que tener objeto 